package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"platform-go-challenge/graph"
	"platform-go-challenge/graph/model"
	"platform-go-challenge/models"
)

// ID is the resolver for the id field.
func (r *audienceResolver) ID(ctx context.Context, obj *models.Audience) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateAudience is the resolver for the createAudience field.
func (r *mutationResolver) CreateAudience(ctx context.Context, input model.NewAudience) (*models.Audience, error) {
	audience := &models.Audience{
		Gender:        input.Gender,
		BirthCountry:  input.Birthcountry,
		AgeGroup:      input.Agegroup,
		DailyHours:    input.Dailyhours,
		NoOfPurchases: input.Noofpurchases,
	}

	if err := r.DB.Create(audience).Error; err != nil {
		return nil, err
	}

	return audience, nil
}

// UpdateAudience is the resolver for the updateAudience field.
func (r *mutationResolver) UpdateAudience(ctx context.Context, id string, input model.UpdateAudience) (*models.Audience, error) {
	var audience models.Audience
	if err := r.DB.First(&audience, id).Error; err != nil {
		return nil, fmt.Errorf("audience not found")
	}

	if input.Gender != nil {
		audience.Gender = *input.Gender
	}
	if input.Birthcountry != nil {
		audience.BirthCountry = *input.Birthcountry
	}
	if input.Agegroup != nil {
		audience.AgeGroup = *input.Agegroup
	}
	if input.Dailyhours != nil {
		audience.DailyHours = *input.Dailyhours
	}
	if input.Noofpurchases != nil {
		audience.NoOfPurchases = *input.Noofpurchases
	}

	if err := r.DB.Save(&audience).Error; err != nil {
		return nil, err
	}

	return &audience, nil
}

// DeleteAudience is the resolver for the deleteAudience field.
func (r *mutationResolver) DeleteAudience(ctx context.Context, id string) (bool, error) {
	var audience models.Audience
	if err := r.DB.Delete(&audience, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Audiences is the resolver for the audiences field.
func (r *queryResolver) Audiences(ctx context.Context) ([]*models.Audience, error) {
	var audiences []*models.Audience
	if err := r.DB.Find(&audiences).Error; err != nil {
		return nil, err
	}
	return audiences, nil
}

// Audience is the resolver for the audience field.
func (r *queryResolver) Audience(ctx context.Context, id string) (*models.Audience, error) {
	var audience models.Audience
	if err := r.DB.First(&audience, id).Error; err != nil {
		return nil, fmt.Errorf("audience not found")
	}
	return &audience, nil
}

// Audience returns graph.AudienceResolver implementation.
func (r *Resolver) Audience() graph.AudienceResolver { return &audienceResolver{r} }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type audienceResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
