package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"platform-go-challenge/graph"
	"platform-go-challenge/graph/model"
	"platform-go-challenge/models"
)

// ID is the resolver for the id field.
func (r *chartResolver) ID(ctx context.Context, obj *models.Chart) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateChart is the resolver for the createChart field.
func (r *mutationResolver) CreateChart(ctx context.Context, input model.NewChart) (*models.Chart, error) {
	chart := &models.Chart{
		Title:      input.Title,
		XAxisTitle: input.Xaxistitle,
		YAxisTitle: input.Yaxistitle,
	}

	if err := r.DB.Create(chart).Error; err != nil {
		return nil, err
	}

	return chart, nil
}

// UpdateChart is the resolver for the updateChart field.
func (r *mutationResolver) UpdateChart(ctx context.Context, id string, input model.UpdateChart) (*models.Chart, error) {
	var chart models.Chart
	if err := r.DB.First(&chart, id).Error; err != nil {
		return nil, fmt.Errorf("chart not found")
	}

	if input.Title != nil {
		chart.Title = *input.Title
	}
	if input.Xaxistitle != nil {
		chart.XAxisTitle = *input.Xaxistitle
	}
	if input.Yaxistitle != nil {
		chart.YAxisTitle = *input.Yaxistitle
	}

	if err := r.DB.Save(&chart).Error; err != nil {
		return nil, err
	}

	return &chart, nil
}

// DeleteChart is the resolver for the deleteChart field.
func (r *mutationResolver) DeleteChart(ctx context.Context, id string) (bool, error) {
	var chart models.Chart
	if err := r.DB.Delete(&chart, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Charts is the resolver for the charts field.
func (r *queryResolver) Charts(ctx context.Context) ([]*models.Chart, error) {
	var charts []*models.Chart
	if err := r.DB.Find(&charts).Error; err != nil {
		return nil, err
	}
	return charts, nil
}

// Chart is the resolver for the chart field.
func (r *queryResolver) Chart(ctx context.Context, id string) (*models.Chart, error) {
	var chart models.Chart
	if err := r.DB.First(&chart, id).Error; err != nil {
		return nil, fmt.Errorf("chart not found")
	}
	return &chart, nil
}

// Chart returns graph.ChartResolver implementation.
func (r *Resolver) Chart() graph.ChartResolver { return &chartResolver{r} }

type chartResolver struct{ *Resolver }
