package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"platform-go-challenge/graph"
	"platform-go-challenge/graph/model"
	"platform-go-challenge/models"
)

// ID is the resolver for the id field.
func (r *insightResolver) ID(ctx context.Context, obj *models.Insight) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateInsight is the resolver for the createInsight field.
func (r *mutationResolver) CreateInsight(ctx context.Context, input model.NewInsight) (*models.Insight, error) {
	insight := &models.Insight{
		Text: input.Text,
	}

	if err := r.DB.Create(insight).Error; err != nil {
		return nil, err
	}

	return insight, nil
}

// UpdateInsight is the resolver for the updateInsight field.
func (r *mutationResolver) UpdateInsight(ctx context.Context, id string, input model.UpdateInsight) (*models.Insight, error) {
	var insight models.Insight
	if err := r.DB.First(&insight, id).Error; err != nil {
		return nil, fmt.Errorf("insight not found")
	}

	if input.Text != nil {
		insight.Text = *input.Text
	}

	if err := r.DB.Save(&insight).Error; err != nil {
		return nil, err
	}

	return &insight, nil
}

// DeleteInsight is the resolver for the deleteInsight field.
func (r *mutationResolver) DeleteInsight(ctx context.Context, id string) (bool, error) {
	var insight models.Insight
	if err := r.DB.Delete(&insight, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Insights is the resolver for the insights field.
func (r *queryResolver) Insights(ctx context.Context) ([]*models.Insight, error) {
	var insights []*models.Insight
	if err := r.DB.Find(&insights).Error; err != nil {
		return nil, err
	}
	return insights, nil
}

// Insight is the resolver for the insight field.
func (r *queryResolver) Insight(ctx context.Context, id string) (*models.Insight, error) {
	var insight models.Insight
	if err := r.DB.First(&insight, id).Error; err != nil {
		return nil, fmt.Errorf("insight not found")
	}
	return &insight, nil
}

// Insight returns graph.InsightResolver implementation.
func (r *Resolver) Insight() graph.InsightResolver { return &insightResolver{r} }

type insightResolver struct{ *Resolver }
