package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"platform-go-challenge/graph"
	"platform-go-challenge/graph/model"
	"platform-go-challenge/models"
)

// CreateUserFavourite is the resolver for the createUserFavourite field.
func (r *mutationResolver) CreateUserFavourite(ctx context.Context, input model.NewUserFavourite) (*models.UserFavourite, error) {
	userfavourite := &models.UserFavourite{
		UserID:  uint(input.Userid),
		Type:    input.Type,
		AssetID: uint(input.Assetid),
	}

	if err := r.DB.Create(userfavourite).Error; err != nil {
		return nil, err
	}

	return userfavourite, nil
}

// UpdateUserFavourite is the resolver for the updateUserFavourite field.
func (r *mutationResolver) UpdateUserFavourite(ctx context.Context, id string, input model.UpdateUserFavourite) (*models.UserFavourite, error) {
	var userfavourite models.UserFavourite
	if err := r.DB.First(&userfavourite, id).Error; err != nil {
		return nil, fmt.Errorf("userfavourite not found")
	}

	if input.Userid != nil {
		userfavourite.UserID = uint(*input.Userid)
	}
	if input.Type != nil {
		userfavourite.Type = *input.Type
	}
	if input.Assetid != nil {
		userfavourite.AssetID = uint(*input.Assetid)
	}

	if err := r.DB.Save(&userfavourite).Error; err != nil {
		return nil, err
	}

	return &userfavourite, nil
}

// DeleteUserFavourite is the resolver for the deleteUserFavourite field.
func (r *mutationResolver) DeleteUserFavourite(ctx context.Context, id string) (bool, error) {
	var userfavourite models.UserFavourite
	if err := r.DB.Delete(&userfavourite, id).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Userfavourites is the resolver for the userfavourites field.
func (r *queryResolver) Userfavourites(ctx context.Context) ([]*models.UserFavourite, error) {
	var userfavourites []*models.UserFavourite
	if err := r.DB.Find(&userfavourites).Error; err != nil {
		return nil, err
	}
	return userfavourites, nil
}

// Userfavourite is the resolver for the userfavourite field.
func (r *queryResolver) Userfavourite(ctx context.Context, id string) (*models.UserFavourite, error) {
	var userfavourite models.UserFavourite
	if err := r.DB.First(&userfavourite, id).Error; err != nil {
		return nil, fmt.Errorf("userfavourite not found")
	}
	return &userfavourite, nil
}

// UserfavouritesByUser is the resolver for the userfavouritesByUser field.
func (r *queryResolver) UserfavouritesByUser(ctx context.Context, userid int) ([]*models.UserFavourite, error) {
	var userfavourites []*models.UserFavourite
	if err := r.DB.Where("user_id = ?", userid).Find(&userfavourites).Error; err != nil {
		return nil, err
	}
	return userfavourites, nil
}

// ID is the resolver for the id field.
func (r *userFavouriteResolver) ID(ctx context.Context, obj *models.UserFavourite) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Userid is the resolver for the userid field.
func (r *userFavouriteResolver) Userid(ctx context.Context, obj *models.UserFavourite) (int, error) {
	return int(obj.UserID), nil
}

// Assetid is the resolver for the assetid field.
func (r *userFavouriteResolver) Assetid(ctx context.Context, obj *models.UserFavourite) (int, error) {
	return int(obj.AssetID), nil
}

// UserFavourite returns graph.UserFavouriteResolver implementation.
func (r *Resolver) UserFavourite() graph.UserFavouriteResolver { return &userFavouriteResolver{r} }

type userFavouriteResolver struct{ *Resolver }
