package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"platform-go-challenge/graph"
	"platform-go-challenge/graph/model"
	"platform-go-challenge/models"
)

// CreateUserStar is the resolver for the createUserStar field.
func (r *mutationResolver) CreateUserStar(ctx context.Context, input model.NewUserStar) (*models.UserStar, error) {
	panic(fmt.Errorf("not implemented: CreateUserStar - createUserStar"))
}

// UpdateUserStar is the resolver for the updateUserStar field.
func (r *mutationResolver) UpdateUserStar(ctx context.Context, id string, input model.UpdateUserStar) (*models.UserStar, error) {
	panic(fmt.Errorf("not implemented: UpdateUserStar - updateUserStar"))
}

// DeleteUserStar is the resolver for the deleteUserStar field.
func (r *mutationResolver) DeleteUserStar(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUserStar - deleteUserStar"))
}

// Userstars is the resolver for the userstars field.
func (r *queryResolver) Userstars(ctx context.Context) ([]*models.UserStar, error) {
	panic(fmt.Errorf("not implemented: Userstars - userstars"))
}

// Userstar is the resolver for the userstar field.
func (r *queryResolver) Userstar(ctx context.Context, id string) (*models.UserStar, error) {
	panic(fmt.Errorf("not implemented: Userstar - userstar"))
}

// ID is the resolver for the id field.
func (r *userStarResolver) ID(ctx context.Context, obj *models.UserStar) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Userid is the resolver for the userid field.
func (r *userStarResolver) Userid(ctx context.Context, obj *models.UserStar) (int, error) {
	panic(fmt.Errorf("not implemented: Userid - userid"))
}

// Assetid is the resolver for the assetid field.
func (r *userStarResolver) Assetid(ctx context.Context, obj *models.UserStar) (int, error) {
	panic(fmt.Errorf("not implemented: Assetid - assetid"))
}

// UserStar returns graph.UserStarResolver implementation.
func (r *Resolver) UserStar() graph.UserStarResolver { return &userStarResolver{r} }

type userStarResolver struct{ *Resolver }
