// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"platform-go-challenge/models"
)

type Mutation struct {
}

type NewAudience struct {
	Gender        string `json:"gender"`
	Birthcountry  string `json:"birthcountry"`
	Agegroup      string `json:"agegroup"`
	Dailyhours    int    `json:"dailyhours"`
	Noofpurchases int    `json:"noofpurchases"`
}

type NewChart struct {
	Title      string `json:"title"`
	Xaxistitle string `json:"xaxistitle"`
	Yaxistitle string `json:"yaxistitle"`
}

type NewInsight struct {
	Text string `json:"text"`
}

type NewUserStar struct {
	Userid  int    `json:"userid"`
	Type    string `json:"type"`
	Assetid int    `json:"assetid"`
}

type Query struct {
}

type UpdateAudience struct {
	Gender        *string `json:"gender,omitempty"`
	Birthcountry  *string `json:"birthcountry,omitempty"`
	Agegroup      *string `json:"agegroup,omitempty"`
	Dailyhours    *int    `json:"dailyhours,omitempty"`
	Noofpurchases *int    `json:"noofpurchases,omitempty"`
}

type UpdateChart struct {
	Title      *string `json:"title,omitempty"`
	Xaxistitle *string `json:"xaxistitle,omitempty"`
	Yaxistitle *string `json:"yaxistitle,omitempty"`
}

type UpdateInsight struct {
	Text *string `json:"text,omitempty"`
}

type UpdateUserStar struct {
	Userid  *int    `json:"userid,omitempty"`
	Type    *string `json:"type,omitempty"`
	Assetid *int    `json:"assetid,omitempty"`
}

type UserStared struct {
	Userid   int                `json:"userid"`
	Audience []*models.Audience `json:"audience"`
	Chart    []*models.Chart    `json:"chart"`
	Insight  []*models.Insight  `json:"insight"`
}
