// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewAudience struct {
	Gender        string `json:"gender"`
	Birthcountry  string `json:"birthcountry"`
	Agegroup      string `json:"agegroup"`
	Dailyhours    int    `json:"dailyhours"`
	Noofpurchases int    `json:"noofpurchases"`
}

type Query struct {
}

type UpdateAudience struct {
	Gender        *string `json:"gender,omitempty"`
	Birthcountry  *string `json:"birthcountry,omitempty"`
	Agegroup      *string `json:"agegroup,omitempty"`
	Dailyhours    *int    `json:"dailyhours,omitempty"`
	Noofpurchases *int    `json:"noofpurchases,omitempty"`
}
